FROM openjdk:8
WORKDIR /app
COPY target/Newspaper_project-0.0.1-SNAPSHOT.jar /app/Newspaper_project-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/Newspaper_project-0.0.1-SNAPSHOT.jar"]